### ISSUE TITLE
The problem when running the baseline FIM

### ISSUE THREAD

**Issue by Snnzhao** [Veason-silverbullet/NNR#1]
When running the baseline FIM on A100(40GB), the training time is too long (over 15hrs can not finish an epoch).
I try to maximize the bachsize, but the situation is not solved. Moreover, the volatile GPU util is 20%.
What's the problem?
How much time is needed, and how much computing resource is needed?

**Comment by Veason-silverbullet** [comment]
This is because Pytorch selects the slow 3D-CNN operator. To solve this problem, please modify the code in config.py (line 108 and 109):

from
`torch.backends.cudnn.benchmark = False
  torch.backends.cudnn.deterministic = True`
to
`torch.backends.cudnn.benchmark = True
  torch.backends.cudnn.deterministic = False`

I set the `cudnn.benchmark` and `cudnn.deterministic` to make all the experiment results reproducible. For FIM, you can modify the above options.

**Comment by Snnzhao** [comment]
The problem is solved. Thanks for replying.
